### ISSUE TITLE
How i can get data from devices connected to ports (Principally MAC address) from a Switch

### ISSUE THREAD

**Issue by pablofloreswittich** [unpoller/unifi#55]
I am trying to get data from all devices (Clientes, APs, USW, Gateways) connected to ports (Principally MAC address) 
I am itereting each port but the mac is empty (it shows a blank space)
in unifi controller webpage it shows the MAC, but i can't get it with the unpoller 
can u help me?

Here is my code and output:
![image](https://user-images.githubusercontent.com/45402057/134350503-d0cb1ac9-9d19-43bb-9dc6-d929a9c1a1c6.png)
![image](https://user-images.githubusercontent.com/45402057/134350542-1127a740-a046-48de-b134-5b59cf983811.png)

**Comment by davidnewhall** [comment]
That's a picture of code, not actually code. It's also missing portions, so no one can use that to reproduce your behavior. Here's the same answer I provided on Discord before you posted this:
>  I'm not seeing anywhere in the code that messes with client mac addresses nor the mac addresses in the port tables. I suspect the API is not providing them. I get the same result as you.  The example in the repo shows how to loop each client. You can get the switch MAC and client MAC there.

**This library just pulls the API data from your controller. I recommend pulling that data directly (curl), yourself, and inspecting it, so you know what's available.**

**Comment by pablofloreswittich** [comment]
This is the code, thank you very much for your help, how do I do what you told me? ( pulling all data directly)

**Comment by wade-p** [comment]
You can use cURL to pull the data, the API endpoint links are in types.go, the device endpoint you're looking for is here: https://github.com/unpoller/unifi/blob/82e0d2cb4da1a28e0e057cc36dca38f5bd9ced56/types.go#L36 

So if you wanted to pull from curl, you could go to the page in your browser, select a request to the API, select copy as curl and then tweak it a bit.

For example:

```
 curl 'https://127.0.0.18443/api/s/default/stat/device' -H 'User-Agent: Foo' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://127.0.0.1:8443/manage/default/clients' -H 'X-Csrf-Token: <a token here>' -H 'Connection: keep-alive' -H 'Cookie: unifises=<a cookie here>' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -o - | gunzip
```

the `-o - | gunzip` does two things, one sends data to your terminal, then pipes it to gunzip, which is important since we're asking for gzip encoding (compressed data)

Now, the actual output of this endpoint does not contain the data you're looking for:

```
"port_table":
            [
                {
                    "aggregated_by": "<SOME VALUE/>",
                    "autoneg": "<SOME VALUE/>",
                    "bytes-r": "<SOME VALUE/>",
                    "enable": "<SOME VALUE/>",
                    "flowctrl_rx": "<SOME VALUE/>",
                    "flowctrl_tx": "<SOME VALUE/>",
                    "full_duplex": "<SOME VALUE/>",
                    "is_uplink": "<SOME VALUE/>",
                    "jumbo": "<SOME VALUE/>",
                    "masked": "<SOME VALUE/>",
                    "media": "<SOME VALUE/>",
                    "name": "Port <SOME VALUE/>",
                    "op_mode": "<SOME VALUE/>",
                    "port_idx": "<SOME VALUE/>",
                    "port_poe": "<SOME VALUE/>",
                    "portconf_id": "<SOME VALUE/>",
                    "rx_broadcast": "<SOME VALUE/>",
                    "rx_bytes": "<SOME VALUE/>",
                    "rx_bytes-r": "<SOME VALUE/>",
                    "rx_dropped": "<SOME VALUE/>",
                    "rx_errors": "<SOME VALUE/>",
                    "rx_multicast": "<SOME VALUE/>",
                    "rx_packets": "<SOME VALUE/>",
                    "speed": "<SOME VALUE/>",
                    "speed_caps": "<SOME VALUE/>",
                    "tx_broadcast": "<SOME VALUE/>",
                    "tx_bytes": "<SOME VALUE/>",
                    "tx_bytes-r": "<SOME VALUE/>",
                    "tx_dropped": "<SOME VALUE/>",
                    "tx_errors": "<SOME VALUE/>",
                    "tx_multicast": "<SOME VALUE/>",
                    "tx_packets": "<SOME VALUE/>",
                    "up": "<SOME VALUE/>",
                },
```

This is coming from a controller v6.5.55

To get the mapping you want, you'll need to combine the above data with the data from GetClients.  If it's wireless it could have both a `ap_mac` and `sw_mac`, wired clients should only have `sw_mac`. They also have a `sw_port`, you can then do a reverse lookup, or build a map of devices by their mac, and print the info you want.

**Comment by davidnewhall** [comment]
> This is the code, thank you very much for your help, how do I do what you told me? ( pulling all data directly)

Sorry I missed your question. Thank you to @wade-p for the detailed answer.

You can also run `unifi-poller -c config.file -j d` to print out devices, and `unifi-poller -c config.file -j c` to print out clients. This is a direct JSON dump from the controller as curl would do it. You just need to have a config file with your unifi username and password in it, so poller can handle the login and cookies.

**Comment by platinummonkey** [comment]
this looks solved, closing this 👍
