### ISSUE TITLE
Feature request: configurable client data collection

### ISSUE THREAD

**Issue by marcg1** [unpoller/unifi#56]
Please consider making client data collection configurable: enabled or disabled.  For certain PII-sensitive use cases, MD5 obfuscation may not be adequate.  If a user's MAC address or name is known, for example, the obfuscated version could be calculated by an attacker and then tracked in the obfuscated data.

unpoller is a great contribution to the community ... thanks!

**Comment by platinummonkey** [comment]
to clarify are you asking the api & json parsing in this repo to opt-out or the https://github.com/unpoller/unpoller integrations to have a way to opt out of certain tags/metrics?

**Comment by marcg1** [comment]
The request is for an option to have unpoller
- not collect MAC address and device name from the Ubiquiti equipment, or
- if that is not possible, not store that MAC address and device name in Prometheus/InfluxDB/etc.

Thanks!

**Comment by platinummonkey** [comment]
Really I believe only option 2 is possible, and something I can look into. The APIs by the vendor likely lack exclusion filtering functionality

**Comment by marcg1** [comment]
Sounds good, thanks.  The use case here is a third-party, e.g., MSP, 
monitoring network performance (at the request of the equipment owner).  
They'd rather not have the risk/responsibility of managing end-users' 
PII.  With Option 2, they can at least say that, while the PII is sent 
to them via a secure connection, they don't store or process it.

Marc

**Comment by platinummonkey** [comment]
looking at this, there is a `hash_pii` function in unpoller that will hash this. Does that suffice?

**Comment by marcg1** [comment]
My understanding is that `hash_pii` creates a simple MD5 hash of the user information.  A bad actor with knowledge of the client name and MAC could compute the hash themselves, and then track the deterministic hashed versions in the stored unpoller results.  It's much better from a security and privacy perspective to not have the client name and MAC address in the stored data, hashed or not.

Thanks!

**Comment by marcg1** [comment]
So, `drop_pii = true` in the config file to enable PII discard?  

This is fantastic and a big privacy upgrade for installations that need it ... thanks!

**Comment by platinummonkey** [comment]
Yes, needs to be documented still - on my todo
