### ISSUE TITLE
Question: PDU Power Pro - Outlet stats

### ISSUE THREAD

**Issue by oester** [unpoller/unifi#74]
It looks like you have the PDU per-outlet stats (power, etc) but I can't see how to pull them via the API or graph them in Grafana. Can you tell me how to access them?

**Comment by platinummonkey** [comment]
Can you describe what you've tried and more information about your specific setup.

**Comment by oester** [comment]
OK, I had forgotten  about this, Let me re-visit here and provide an update. I just updated to the latest unpoller version.

**Comment by oester** [comment]
I think we can close this now, and I see the outlet power listed in the prometheus stats now, after upgrading to latest version.
