### ISSUE TITLE
client.ApName output nothing

### ISSUE THREAD

**Issue by Deniskaponchik** [unpoller/unifi#90]
log.Println(len(clients), "Clients connected:")
	for i, client := range clients {
		log.Println(i+1, client.ID, client.Hostname, client.IP, client.Name, ### client.ApName)
	}

client.ApName output nothing. Please, look at the screenshot:
![image](https://github.com/unpoller/unifi/assets/13918231/d491f9b9-af84-48e8-a5ea-0990586f258f)

**Comment by platinummonkey** [comment]
Just paste the screenshot. GitHub hosts images natively

**Comment by Deniskaponchik** [comment]
> Just paste the screenshot. GitHub hosts images natively

done

**Comment by davidnewhall** [comment]
IIRC ApName is only filled in under certain circumstance and it's not a native field in the UniFi API. In other words, you need to do another request to get the apMAC->apName map.

**Comment by Deniskaponchik** [comment]
Thanks!
